steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=https://techmind-backend-447002759938.southamerica-east1.run.app'
      - '--build-arg'
      - 'VITE_SWAGGER_URL=https://techmind-backend-447002759938.southamerica-east1.run.app/swagger-ui.html'
      - '-t'
      - 'southamerica-east1-docker.pkg.dev/techmind-505119/techmind/techmind-frontend:latest'
      - '.'

images:
  - 'southamerica-east1-docker.pkg.dev/techmind-505119/techmind/techmind-frontend:latest'
