CREATE TABLE artigos_classificados (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(200 CHAR) NOT NULL,
    texto CLOB NOT NULL,
    autores VARCHAR2(255 CHAR),
    link VARCHAR2(500 CHAR),
    ano NUMBER(4),
    categoria VARCHAR2(80 CHAR) NOT NULL,
    probabilidade NUMBER(19, 10) NOT NULL,
    status VARCHAR2(20 CHAR) NOT NULL,
    criado_em TIMESTAMP NOT NULL
);

CREATE TABLE artigos_informacoes (
    artigo_id NUMBER NOT NULL,
    informacao VARCHAR2(100 CHAR),
    CONSTRAINT fk_artigos_informacoes_artigo
        FOREIGN KEY (artigo_id) REFERENCES artigos_classificados (id)
);

CREATE INDEX idx_artigos_classificados_criado_em
    ON artigos_classificados (criado_em);
