ALTER TABLE artigos_classificados ADD categoria_original VARCHAR2(80 CHAR);

UPDATE artigos_classificados SET categoria_original = categoria WHERE categoria_original IS NULL;

CREATE TABLE artigos_feedback (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artigo_id NUMBER NOT NULL,
    categoria_original VARCHAR2(80 CHAR),
    categoria_corrigida VARCHAR2(80 CHAR),
    probabilidade_original FLOAT(53),
    decisao VARCHAR2(20 CHAR) NOT NULL,
    decidido_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_artigos_feedback_artigo
        FOREIGN KEY (artigo_id) REFERENCES artigos_classificados (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_artigos_feedback_artigo_id
    ON artigos_feedback (artigo_id);
