spring:
  config:
    activate:
      on-profile: integration
  datasource:
    url: jdbc:h2:mem:techmind;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    hibernate.ddl-auto: validate
  flyway:
    locations: classpath:db/migration/h2
oci:
  database:
    enabled: false
ml-service:
  url: ${ML_SERVICE_URL}
  mock-enabled: false
