CREATE TABLE artigos_classificados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    texto CLOB NOT NULL,
    autores VARCHAR(255),
    link VARCHAR(500),
    ano INTEGER,
    categoria VARCHAR(80) NOT NULL,
    probabilidade DOUBLE NOT NULL,
    status VARCHAR(20) NOT NULL,
    criado_em TIMESTAMP NOT NULL
);

CREATE TABLE artigos_informacoes (
    artigo_id BIGINT NOT NULL,
    informacao VARCHAR(100),
    CONSTRAINT fk_artigos_informacoes_artigo
        FOREIGN KEY (artigo_id) REFERENCES artigos_classificados (id)
);

CREATE INDEX idx_artigos_classificados_criado_em
    ON artigos_classificados (criado_em);
