ALTER TABLE artigos_classificados ADD COLUMN categoria_original VARCHAR(80);

UPDATE artigos_classificados SET categoria_original = categoria WHERE categoria_original IS NULL;

CREATE TABLE artigos_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artigo_id BIGINT NOT NULL,
    categoria_original VARCHAR(80),
    categoria_corrigida VARCHAR(80),
    probabilidade_original DOUBLE,
    decisao VARCHAR(20) NOT NULL,
    decidido_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_artigos_feedback_artigo
        FOREIGN KEY (artigo_id) REFERENCES artigos_classificados (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_artigos_feedback_artigo_id
    ON artigos_feedback (artigo_id);
